# Form implementation generated from reading ui file 'user_Register_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(352, 321)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.user_regiser_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_regiser_title.setGeometry(QtCore.QRect(90, 10, 221, 20))
        self.user_regiser_title.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"color: rgb(85, 0, 255);")
        self.user_regiser_title.setObjectName("user_regiser_title")
        self.user_regiser_usernameLable = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_regiser_usernameLable.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.user_regiser_usernameLable.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.user_regiser_usernameLable.setObjectName("user_regiser_usernameLable")
        self.user_regiser_passwordLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_regiser_passwordLabel.setGeometry(QtCore.QRect(40, 90, 71, 16))
        self.user_regiser_passwordLabel.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.user_regiser_passwordLabel.setObjectName("user_regiser_passwordLabel")
        self.user_regiser_conpasswordLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_regiser_conpasswordLabel.setGeometry(QtCore.QRect(40, 120, 101, 16))
        self.user_regiser_conpasswordLabel.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.user_regiser_conpasswordLabel.setObjectName("user_regiser_conpasswordLabel")
        self.user_regiser_emaillabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_regiser_emaillabel.setGeometry(QtCore.QRect(40, 150, 51, 16))
        self.user_regiser_emaillabel.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.user_regiser_emaillabel.setObjectName("user_regiser_emaillabel")
        self.user_regiser_to_loginlabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_regiser_to_loginlabel.setGeometry(QtCore.QRect(67, 260, 51, 16))
        self.user_regiser_to_loginlabel.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"")
        self.user_regiser_to_loginlabel.setObjectName("user_regiser_to_loginlabel")
        self.user_regiser_usernamelineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user_regiser_usernamelineEdit.setGeometry(QtCore.QRect(150, 60, 161, 20))
        self.user_regiser_usernamelineEdit.setObjectName("user_regiser_usernamelineEdit")
        self.user_regiser_passwordlineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user_regiser_passwordlineEdit.setGeometry(QtCore.QRect(150, 90, 161, 20))
        self.user_regiser_passwordlineEdit.setObjectName("user_regiser_passwordlineEdit")
        self.user_regiser_conpasswordlineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user_regiser_conpasswordlineEdit.setGeometry(QtCore.QRect(150, 120, 161, 20))
        self.user_regiser_conpasswordlineEdit.setObjectName("user_regiser_conpasswordlineEdit")
        self.user_regiser_emaillineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user_regiser_emaillineEdit.setGeometry(QtCore.QRect(150, 150, 161, 20))
        self.user_regiser_emaillineEdit.setObjectName("user_regiser_emaillineEdit")
        self.user_regiser_phonelineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user_regiser_phonelineEdit.setGeometry(QtCore.QRect(150, 180, 161, 20))
        self.user_regiser_phonelineEdit.setObjectName("user_regiser_phonelineEdit")
        self.user_regiser_phonelabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_regiser_phonelabel.setGeometry(QtCore.QRect(40, 180, 91, 16))
        self.user_regiser_phonelabel.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.user_regiser_phonelabel.setObjectName("user_regiser_phonelabel")
        self.user_regiser_cancelbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.user_regiser_cancelbutton.setGeometry(QtCore.QRect(150, 210, 56, 17))
        self.user_regiser_cancelbutton.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(255, 170, 127);")
        self.user_regiser_cancelbutton.setObjectName("user_regiser_cancelbutton")
        self.user_regiser_registerbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.user_regiser_registerbutton.setGeometry(QtCore.QRect(250, 210, 56, 17))
        self.user_regiser_registerbutton.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(255, 170, 127);")
        self.user_regiser_registerbutton.setObjectName("user_regiser_registerbutton")
        self.user_regiser_backbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.user_regiser_backbutton.setGeometry(QtCore.QRect(10, 260, 56, 17))
        self.user_regiser_backbutton.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"color: rgb(0, 0, 255);")
        self.user_regiser_backbutton.setObjectName("user_regiser_backbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 352, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.user_regiser_title.setText(_translate("MainWindow", "Enter Details To Register"))
        self.user_regiser_usernameLable.setText(_translate("MainWindow", "Username:"))
        self.user_regiser_passwordLabel.setText(_translate("MainWindow", "Password:"))
        self.user_regiser_conpasswordLabel.setText(_translate("MainWindow", "Confirm Password:"))
        self.user_regiser_emaillabel.setText(_translate("MainWindow", "Email:"))
        self.user_regiser_to_loginlabel.setText(_translate("MainWindow", "to login"))
        self.user_regiser_usernamelineEdit.setPlaceholderText(_translate("MainWindow", "username"))
        self.user_regiser_passwordlineEdit.setPlaceholderText(_translate("MainWindow", "password"))
        self.user_regiser_conpasswordlineEdit.setPlaceholderText(_translate("MainWindow", "confirm password"))
        self.user_regiser_emaillineEdit.setPlaceholderText(_translate("MainWindow", "email"))
        self.user_regiser_phonelineEdit.setPlaceholderText(_translate("MainWindow", "phone number"))
        self.user_regiser_phonelabel.setText(_translate("MainWindow", "Phone Number:"))
        self.user_regiser_cancelbutton.setText(_translate("MainWindow", "Cancel"))
        self.user_regiser_registerbutton.setText(_translate("MainWindow", "Register"))
        self.user_regiser_backbutton.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
