# Form implementation generated from reading ui file 'user_login_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(338, 345)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.user_login_titlelabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_login_titlelabel.setGeometry(QtCore.QRect(20, 10, 301, 20))
        self.user_login_titlelabel.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"color: rgb(85, 0, 255);")
        self.user_login_titlelabel.setObjectName("user_login_titlelabel")
        self.user_login_usernamelabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_login_usernamelabel.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.user_login_usernamelabel.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.user_login_usernamelabel.setObjectName("user_login_usernamelabel")
        self.user_login_passwordlabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_login_passwordlabel.setGeometry(QtCore.QRect(20, 100, 61, 16))
        self.user_login_passwordlabel.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.user_login_passwordlabel.setObjectName("user_login_passwordlabel")
        self.user_login_usernamelineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user_login_usernamelineEdit.setGeometry(QtCore.QRect(90, 60, 181, 21))
        self.user_login_usernamelineEdit.setObjectName("user_login_usernamelineEdit")
        self.user_login_passwordlineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user_login_passwordlineEdit.setGeometry(QtCore.QRect(90, 100, 181, 20))
        self.user_login_passwordlineEdit.setObjectName("user_login_passwordlineEdit")
        self.user_login_registerlabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_login_registerlabel.setGeometry(QtCore.QRect(190, 190, 111, 16))
        self.user_login_registerlabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.user_login_registerlabel.setObjectName("user_login_registerlabel")
        self.user_login_cancelButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.user_login_cancelButton.setGeometry(QtCore.QRect(90, 140, 56, 17))
        self.user_login_cancelButton.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(170, 170, 127);")
        self.user_login_cancelButton.setObjectName("user_login_cancelButton")
        self.user_login_loginButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.user_login_loginButton.setGeometry(QtCore.QRect(180, 140, 56, 17))
        self.user_login_loginButton.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(170, 170, 127);")
        self.user_login_loginButton.setObjectName("user_login_loginButton")
        self.user_login_registerButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.user_login_registerButton.setGeometry(QtCore.QRect(200, 210, 61, 21))
        self.user_login_registerButton.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"Times New Roman\";\n"
"color: rgb(85, 170, 0);")
        self.user_login_registerButton.setObjectName("user_login_registerButton")
        self.user_login_companyLoginButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.user_login_companyLoginButton.setGeometry(QtCore.QRect(10, 240, 56, 21))
        self.user_login_companyLoginButton.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"color: rgb(0, 0, 255);")
        self.user_login_companyLoginButton.setObjectName("user_login_companyLoginButton")
        self.user_login_exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.user_login_exitButton.setGeometry(QtCore.QRect(10, 280, 56, 17))
        self.user_login_exitButton.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"color: rgb(255, 0, 0);")
        self.user_login_exitButton.setObjectName("user_login_exitButton")
        self.user_login_companyLoginlabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_login_companyLoginlabel.setGeometry(QtCore.QRect(70, 240, 111, 16))
        self.user_login_companyLoginlabel.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.user_login_companyLoginlabel.setObjectName("user_login_companyLoginlabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 338, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login Page"))
        self.user_login_titlelabel.setText(_translate("MainWindow", "Enter Username and Password To Login"))
        self.user_login_usernamelabel.setText(_translate("MainWindow", "Username:"))
        self.user_login_passwordlabel.setText(_translate("MainWindow", "Password:"))
        self.user_login_usernamelineEdit.setPlaceholderText(_translate("MainWindow", "username"))
        self.user_login_passwordlineEdit.setPlaceholderText(_translate("MainWindow", "password"))
        self.user_login_registerlabel.setText(_translate("MainWindow", "Don\'t have an account?"))
        self.user_login_cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.user_login_loginButton.setText(_translate("MainWindow", "Login"))
        self.user_login_registerButton.setText(_translate("MainWindow", "Register"))
        self.user_login_companyLoginButton.setText(_translate("MainWindow", "Login"))
        self.user_login_exitButton.setText(_translate("MainWindow", "Exit"))
        self.user_login_companyLoginlabel.setText(_translate("MainWindow", "as a utiliy company"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
